server:
  port: 8080
  servlet:
    context-path: /api/v1
    encoding:
      charset: utf-8
      enabled: true

spring:
  application:
    name: oneBox
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 2GB
  datasource:
    url: jdbc:postgresql://localhost:5432/one_box
#    url: jdbc:postgresql://postgres:5432/one_box
    driver-class-name: org.postgresql.Driver
    username: one_box
    password: one_box_123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS

storage:
  max-quota: 5368709120 # 5GB

minio:
  port: 9000
  host: localhost
#  host: minio
  access-key: one_box
  secret-key: one_box_123
  bucket: one-box-bucket

management:
  endpoints.web.exposure.include: prometheus
  metrics:
    export.prometheus.enabled: true
    tags.app: oneBox

logging:
  level:
    org:
#      springframework: INFO
      springframework: TRACE
      hibernate: WARN