server:
  port: 8080
  servlet:
    context-path: /api/v1
    encoding:
      charset: utf-8
      enabled: true

spring:
  application:
    name: oneBox
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/one_box
    driver-class-name: org.postgresql.Driver
    username: one_box
    password: one_box_123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS

storage:
  max-quota: 5368709120 # 5GB

minio:
  port: 9000
  host: localhost
  access-key: one_box
  secret-key: one_box_123
  bucket: one-box-bucket

logging:
  level:
    org.springframework: INFO
    org.hibernate: WARN